dist: xenial
language: python

python:
  - 3.6.8
sudo: false

# The apt packages below are needed for sphinx builds
addons:
  apt:
    packages:
      - texlive-latex-extra
      - dvipng
      - graphviz

env:
  global:
    - CRDS_SERVER_URL='https://jwst-crds.stsci.edu'
    - CRDS_PATH='/tmp/crds_cache'
    - NUMPY_VERSION=1.16

matrix:
  # Don't wait for allowed failures
  fast_finish: true
  include:
    # Run tests
    - python: "3.7"
      env: TEST_COMMAND='python setup.py test'
           PIP_DEPENDENCIES='.[test]'

    - python: "3.6.8"
      env: TEST_COMMAND='python setup.py test'
           PIP_DEPENDENCIES='.[test]'

    # Build sphinx documentation with warnings
    - env: TEST_COMMAND='python setup.py build_sphinx -W'
           PIP_DEPENDENCIES='.[docs]'

    # PEP8 check
    - env: TEST_COMMAND='flake8 --count --select=F, E101, E111, E112, E113, E401, E402, E711, E722 --max-line-length=110 jwst'

    # Strict PEP8 check, an allowed failure below
    - env: TEST_COMMAND='flake8 --count jwst'

    allow_failures:
    - env: TEST_COMMAND='flake8 --count jwst'

install:
  - pip install numpy~=$NUMPY_VERSION
  - if [[ -n $PIP_DEPENDENCIES ]]; then pip install -e $PIP_DEPENDENCIES; fi
  - pip install flake8

script: $TEST_COMMAND
